function randomArtefact() {
    const artefacts = [
        "Épée de l'Aube",
        "Amulette du Sorcier",
        "Bouclier du Gardien",
        "Couronne du Roi des Elfes",
        "Arc-en-Ciel de l'Enchanteur",
        "Potion d'Invisibilité",
        "Étoile du Matin Maudite",
        "Grimoire des Ombres",
        "Lance du Paladin",
        "Bâton du Mage",
        "Cape de l'Assassin",
        "Bague de Puissance",
        "Hache du Barbare",
        "Flèche d'Argent",
        "Anneau de Résurrection",
        "Dague du Voleur",
        "Bouclier de la Tortue",
        "Hache de Guerre des Nains",
        "Boussole du Navigateur",
        "Épée de Cristal",
        "Grimoire des Sortilèges",
        "Bâton de la Forêt Enchantée",
        "Écaille du Dragon",
        "Heaume du Chevalier",
        "Bague de l'Empereur",
        "Lance de la Lumière Divine",
        "Sceptre de l'Archimage",
        "Anneau de l'Invisibilité",
        "Gantelet du Géant",
        "Cape du Vagabond",
        "Pierre de Téléportation",
        "Arc d'Émeraude",
        "Talisman de la Sagesse",
        "Lame du Templier",
        "Potion de Guérison",
        "Bouclier du Phénix",
        "Sceptre du Nécromancien",
        "Flèche de Feu",
        "Épée du Roi",
        "Heaume de la Bravoure",
        "Bâton de l'Oracle",
        "Bouclier d'Orion",
        "Livre des Secrets",
        "Bague de l'Éternité",
        "Cape de l'Aventurier",
        "Lame de l'Éclipse",
        "Dague de Vengeance",
        "Épée du Dragon",
        "Amulette du Sage",
        "Lance de la Justice",
        "Anneau de l'Évasion",
        "Bâton de l'Alchimiste",
        "Griffe du Loup-Garou",
        "Bouclier du Chevalier Noir",
        "Lame de la Tempête",
        "Potion de Force",
        "Cape de l'Ombre",
        "Glaive de Glace",
        "Heaume du Dragon",
        "Talisman de la Fortune",
        "Sceptre du Temps",
        "Bague de la Foudre",
        "Arc du Chasseur",
        "Bouclier de la Lune",
        "Épée du Guerrier",
        "Dague de l'Assassin",
        "Livre des Runes",
        "Bâton de l'Enchanteur",
        "Couronne des Rois",
        "Amulette de l'Étoile du Soir",
        "Lance du Temps",
        "Anneau du Magicien",
        "Heaume du Minotaure",
        "Grimoire des Maléfices",
        "Cape du Voyageur",
        "Épée de la Destinée",
        "Lance de la Fureur",
        "Bouclier de la Foi",
        "Bague du Rêveur",
        "Flèche de la Vengeance",
        "Lame de l'Éternité",
        "Sceptre de la Connaissance",
        "Bâton de la Sorcière",
        "Potion de Transformation",
        "Amulette du Dragon Rouge",
        "Heaume du Léviathan",
        "Talisman de l'Éclipse",
        "Épée du Phoenix",
        "Livre des Sortilèges",
        "Dague du Voleur d'Âmes",
        "Bague du Crépuscule",
        "Cape de la Nuit",
        "Bouclier du Griffon",
        "Lame de la Légende",
        "Arc du Chasseur de Dragons",
        "Sceptre du Magus",
        "Heaume du Géant de Pierre",
        "Anneau de l'Immortalité",
        "Grimoire de l'Ombre",

];
    const randNum = Math.floor(Math.random() * 100);
    const artefact = artefacts[randNum];
    document.getElementById('reward').value = artefact;
}

